-- Step 1: Create new enum types (must be in separate transaction from tables using them)
DO $$ BEGIN
  CREATE TYPE "MovementType" AS ENUM (
    'ISSUE', 'RECEIVE', 'RESERVE', 'UNRESERVE', 'RETURN', 'ADJUSTMENT', 'TRANSFER_IN', 'TRANSFER_OUT'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

-- Extend RequestStatus
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'RETURNED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_APPROVED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'READY_TO_ISSUE'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_ISSUED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'BACKORDER'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "RequestStatus" ADD VALUE IF NOT EXISTS 'CLOSED'; EXCEPTION WHEN others THEN NULL; END $$;

-- Extend LineStatus
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'DRAFT'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'REJECTED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'READY_TO_ISSUE'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'PARTIALLY_ISSUED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'RETURNED'; EXCEPTION WHEN others THEN NULL; END $$;
DO $$ BEGIN ALTER TYPE "LineStatus" ADD VALUE IF NOT EXISTS 'SUBSTITUTED'; EXCEPTION WHEN others THEN NULL; END $$;
